/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Panels;

import GreenCoffeeClasses.CoffeeCountry;
import GreenCoffeeClasses.CoffeeGreen;
import GreenCoffeeClasses.CoffeeGreenChangeHistory;
import GreenCoffeeClasses.CoffeeOwner;
import ProductionManagement.LabTest;
import GreenCoffeeClasses.CoffeeType;
import ProductionManagement.DataBaseConnector;
import ProductionManagement.Employee;
import GreenCoffeeClasses.PackType;
import GreenCoffeeClasses.Provider;
import ProductClasses.AromaType;
import ProductClasses.RoastAromaPart;
import ProductClasses.RoastGreenCoffeePart;
import ProductClasses.RoastPart;
import ProductionClasses.ProductionCoffee;
import ProductionManagement.Global;
import java.sql.Timestamp;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.HashSet;

import javax.swing.JOptionPane;
import javax.swing.JSpinner;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Przemysław
 */
public class AddGreenCoffeePanel extends javax.swing.JPanel {

    /**
     * Creates new form AddGreenCoffeeMagazynierPanel
     */
    ArrayList<CoffeeType> alct;
    ArrayList<CoffeeOwner> alco;
    ArrayList<CoffeeCountry> alcc;
    ArrayList<PackType> alpt;
    ArrayList<Provider> alp;
    Employee emp;
    DataBaseConnector dbc = null;

    private void resetInput() {

        checkBoxVermin.setSelected(false);
        comboBoxCoffeeOwner.setSelectedItem(null);
        comboBoxCoffeeType.setSelectedItem(null);
        comboBoxPackType.setSelectedItem(null);
        comboBoxProvider.setSelectedItem(null);
        textFieldContractNumber.setText("");
        textFieldDossierNumber.setText("");
        spinnerPacksNumber.setValue(new Integer(0));
        spinnerCoffeeWeight.setValue(new Float(0));

    }

    public AddGreenCoffeePanel(Employee emp) {
        initComponents();

        this.emp = emp;
        if (dbc == null) {
            dbc = Global.getDataBaseConnector();
        }
        dbc.clearSession();
        dbc.openSession();

        alct = dbc.getCoffeeType();

        Object[] o = alct.toArray();
        Arrays.sort(o);

        comboBoxCoffeeType.removeAllItems();
        for (Object ob : o) {
            CoffeeType ct = (CoffeeType) ob;
            comboBoxCoffeeType.addItem(ct);
        }
        comboBoxCoffeeType.setSelectedItem(null);

        alco = dbc.getCoffeeOwner();
        comboBoxCoffeeOwner.removeAllItems();
        for (CoffeeOwner co : alco) {
            comboBoxCoffeeOwner.addItem(co);
        }
        comboBoxCoffeeOwner.setSelectedItem(null);

        alpt = dbc.getPackType();
        comboBoxPackType.removeAllItems();
        for (PackType pt : alpt) {
            comboBoxPackType.addItem(pt);
        }
        comboBoxPackType.setSelectedItem(null);

        alp = dbc.getProvider();
        o = alp.toArray();
        Arrays.sort(o);

        comboBoxProvider.removeAllItems();
        for (Object ob : o) {
            comboBoxProvider.addItem(ob);
        }
        comboBoxProvider.setSelectedItem(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        labelMain = new javax.swing.JLabel();
        labelCoffeOwner = new javax.swing.JLabel();
        comboBoxCoffeeOwner = new javax.swing.JComboBox();
        comboBoxPackType = new javax.swing.JComboBox();
        labelPackType = new javax.swing.JLabel();
        labelNumberOfPacks = new javax.swing.JLabel();
        labelCoffeeDossierNumber = new javax.swing.JLabel();
        labelContractNumber = new javax.swing.JLabel();
        textFieldContractNumber = new javax.swing.JTextField();
        labelWeight = new javax.swing.JLabel();
        buttonRegisterToLaboratory = new javax.swing.JButton();
        textFieldDossierNumber = new javax.swing.JTextField();
        labelCoffeOwner1 = new javax.swing.JLabel();
        comboBoxCoffeeType = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        comboBoxProvider = new javax.swing.JComboBox();
        checkBoxVermin = new javax.swing.JCheckBox();
        buttonAddNewCoffeeType = new javax.swing.JButton();
        buttonAddNewCoffeeOwner = new javax.swing.JButton();
        buttonAddNewCoffeeProvider = new javax.swing.JButton();
        buttonAddNewPackType = new javax.swing.JButton();
        spinnerCoffeeWeight = new javax.swing.JSpinner(new SpinnerNumberModel(new Float(0), new Float(0),null,new Float(0.01)))
        ;
        spinnerPacksNumber = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();

        button1.setLabel("button1");

        labelMain.setText("Rejestrowanie kawy do badania");

        labelCoffeOwner.setText("Właściciel Kawy");

        labelPackType.setText("Rodzaj Pakownia");

        labelNumberOfPacks.setText("Ilość Opakowań");

        labelCoffeeDossierNumber.setText("Dossier");

        labelContractNumber.setText("Numer Kontraktu");

        labelWeight.setText("Waga [Kg]");

        buttonRegisterToLaboratory.setText("Zarejestruj do badania");
        buttonRegisterToLaboratory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterToLaboratoryActionPerformed(evt);
            }
        });

        labelCoffeOwner1.setText("Typ kawy");

        jLabel1.setText("Producent");

        checkBoxVermin.setText("Szkodniki obecne");

        buttonAddNewCoffeeType.setText("+");
        buttonAddNewCoffeeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddNewCoffeeTypeActionPerformed(evt);
            }
        });

        buttonAddNewCoffeeOwner.setText("+");
        buttonAddNewCoffeeOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddNewCoffeeOwnerActionPerformed(evt);
            }
        });

        buttonAddNewCoffeeProvider.setText("+");
        buttonAddNewCoffeeProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddNewCoffeeProviderActionPerformed(evt);
            }
        });

        buttonAddNewPackType.setText("+");
        buttonAddNewPackType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddNewPackTypeActionPerformed(evt);
            }
        });

        spinnerCoffeeWeight.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), null, Float.valueOf(1.0f)));

        spinnerPacksNumber.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jButton1.setText("Wyczyść");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("#");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMain)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelCoffeOwner1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCoffeOwner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNumberOfPacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCoffeeDossierNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelContractNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldContractNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboBoxCoffeeOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonAddNewCoffeeOwner))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboBoxCoffeeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonAddNewCoffeeType))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboBoxProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonAddNewCoffeeProvider))))
                            .addComponent(textFieldDossierNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(spinnerPacksNumber)))
                    .addComponent(checkBoxVermin)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonRegisterToLaboratory)
                        .addGap(46, 46, 46)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPackType, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxPackType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAddNewPackType))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerCoffeeWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(216, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMain)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxCoffeeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCoffeOwner1)
                    .addComponent(buttonAddNewCoffeeType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxCoffeeOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCoffeOwner)
                    .addComponent(buttonAddNewCoffeeOwner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(buttonAddNewCoffeeProvider))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCoffeeDossierNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDossierNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContractNumber)
                    .addComponent(textFieldContractNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPackType)
                    .addComponent(comboBoxPackType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddNewPackType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumberOfPacks)
                    .addComponent(spinnerPacksNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWeight)
                    .addComponent(spinnerCoffeeWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(27, 27, 27)
                .addComponent(checkBoxVermin)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRegisterToLaboratory)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegisterToLaboratoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterToLaboratoryActionPerformed
        // TODO add your handling code here:
        try {
            dbc.openSession();
            dbc.startTransation();
            java.sql.Timestamp currentTime = new java.sql.Timestamp(System.currentTimeMillis());
            String str = dbc.getMaxLabIdCoffeeGreen();
            String newLabIdStr;
            if (str != null) {
                Integer lastLabId = Integer.parseInt(str.substring(1, 7));

                newLabIdStr = String.format("K%06d", lastLabId + 1);
            } else {
                newLabIdStr = String.format("K%06d", 1);
            }

            CoffeeGreen cg = new CoffeeGreen();

            cg.setArrivalDate(currentTime);
            cg.setCoffeeOwner((CoffeeOwner) comboBoxCoffeeOwner.getSelectedItem());
            cg.setContractNumber(textFieldContractNumber.getText());
            cg.setCoffeeType((CoffeeType) comboBoxCoffeeType.getSelectedItem());
            cg.setDossierNumber(textFieldDossierNumber.getText());
            cg.setCurrentWeight(Global.round((Float) spinnerCoffeeWeight.getValue(), 2));
            cg.setArrivalWeight(cg.getCurrentWeight());
            cg.setState(Global.COFFEE_GREEN_TO_EXAMINE);
            cg.setStoreman(emp);
            cg.setPackType((PackType) comboBoxPackType.getSelectedItem());
            cg.setLabId(newLabIdStr);
            cg.setNumberOfPacks((Integer) spinnerPacksNumber.getValue());
            LabTest ct = new LabTest();
            ct.setVermin(checkBoxVermin.isSelected());
            dbc.saveTransation(ct);
            cg.setLabTest(ct);
            cg.setProvider((Provider) comboBoxProvider.getSelectedItem());
            dbc.saveTransation(cg);

            CoffeeGreenChangeHistory cgch = new CoffeeGreenChangeHistory();
            cgch.setChangeTime(new Timestamp(System.currentTimeMillis()));
            cgch.setChangedBy(emp);
            cgch.setComment("Dostawa - " + cg.getLabId());
            cgch.setWeight(cg.getArrivalWeight());
            cgch.setCoffeeGreen(cg);
            cg.setCoffeeGreenChangeHistory(new HashSet<CoffeeGreenChangeHistory>());
            cg.getCoffeeGreenChangeHistory().add(cgch);

            dbc.saveTransation(cgch);

            JOptionPane.showMessageDialog(null, "Zarejestrowano do badania.", "Informacja", JOptionPane.INFORMATION_MESSAGE);
            dbc.commitTransation();
            // resetInput();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Sprawdź wprowadzone dane", "Błąd", JOptionPane.ERROR_MESSAGE);
            e.printStackTrace();
            return;
        }
    }//GEN-LAST:event_buttonRegisterToLaboratoryActionPerformed

    private void buttonAddNewCoffeeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddNewCoffeeTypeActionPerformed
        String[] option = {"Cofnij"};

        int result = JOptionPane.showOptionDialog(this, new AddGreenCoffeeTypePanel(), "Dodaj nowy typ kawy", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE, null, option, option[0]);

        dbc.openSession();
        dbc.clearSession();
        alct = dbc.getCoffeeType();

        Object[] o = alct.toArray();
        Arrays.sort(o);

        comboBoxCoffeeType.removeAllItems();
        for (Object ob : o) {
            CoffeeType ct = (CoffeeType) ob;
            comboBoxCoffeeType.addItem(ct);
        }
        comboBoxCoffeeType.setSelectedItem(null);


    }//GEN-LAST:event_buttonAddNewCoffeeTypeActionPerformed

    private void buttonAddNewCoffeeOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddNewCoffeeOwnerActionPerformed
        String[] option = {"Cofnij"};

        int result = JOptionPane.showOptionDialog(this, new AddCoffeeOwnerPanel(), "Dodaj nowego właściciela kawy", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE, null, option, option[0]);
        if (JOptionPane.OK_OPTION == result) {
            dbc.openSession();
            dbc.clearSession();
            alco = dbc.getCoffeeOwner();
            comboBoxCoffeeOwner.removeAllItems();
            for (CoffeeOwner co : alco) {
                comboBoxCoffeeOwner.addItem(co);
            }
            comboBoxCoffeeOwner.setSelectedItem(null);

        }
    }//GEN-LAST:event_buttonAddNewCoffeeOwnerActionPerformed

    private void buttonAddNewCoffeeProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddNewCoffeeProviderActionPerformed
        String[] option = {"Cofnij"};
        int result = JOptionPane.showOptionDialog(this, new AddProviderPanel(), "Dodaj nowego dostawcę", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE, null, option, option[0]);
        if (JOptionPane.OK_OPTION == result) {
            dbc.openSession();
            dbc.clearSession();
            alp = dbc.getProvider();
            Object[] o = alp.toArray();
            Arrays.sort(o);

            comboBoxProvider.removeAllItems();
            for (Object ob : o) {
                comboBoxProvider.addItem(ob);
            }
            comboBoxProvider.setSelectedItem(null);
        }
    }//GEN-LAST:event_buttonAddNewCoffeeProviderActionPerformed

    private void buttonAddNewPackTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddNewPackTypeActionPerformed
        String[] option = {"Cofnij"};
        int result = JOptionPane.showOptionDialog(this, new AddPackTypePanel(), "Dodaj nowy typ paczki", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE, null, option, option[0]);
        if (JOptionPane.OK_OPTION == result) {
            dbc.openSession();
            dbc.clearSession();
            alpt = dbc.getPackType();
            comboBoxPackType.removeAllItems();
            for (PackType pt : alpt) {
                comboBoxPackType.addItem(pt);
            }
            comboBoxPackType.setSelectedItem(null);

        }
    }//GEN-LAST:event_buttonAddNewPackTypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        resetInput();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        spinnerCoffeeWeight.setValue(new Float((Integer) spinnerPacksNumber.getValue() * ((PackType) comboBoxPackType.getSelectedItem()).getSize()));
    }//GEN-LAST:event_jButton2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JButton buttonAddNewCoffeeOwner;
    private javax.swing.JButton buttonAddNewCoffeeProvider;
    private javax.swing.JButton buttonAddNewCoffeeType;
    private javax.swing.JButton buttonAddNewPackType;
    private javax.swing.JButton buttonRegisterToLaboratory;
    private javax.swing.JCheckBox checkBoxVermin;
    private javax.swing.JComboBox comboBoxCoffeeOwner;
    private javax.swing.JComboBox comboBoxCoffeeType;
    private javax.swing.JComboBox comboBoxPackType;
    private javax.swing.JComboBox comboBoxProvider;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCoffeOwner;
    private javax.swing.JLabel labelCoffeOwner1;
    private javax.swing.JLabel labelCoffeeDossierNumber;
    private javax.swing.JLabel labelContractNumber;
    private javax.swing.JLabel labelMain;
    private javax.swing.JLabel labelNumberOfPacks;
    private javax.swing.JLabel labelPackType;
    private javax.swing.JLabel labelWeight;
    private javax.swing.JSpinner spinnerCoffeeWeight;
    private javax.swing.JSpinner spinnerPacksNumber;
    private javax.swing.JTextField textFieldContractNumber;
    private javax.swing.JTextField textFieldDossierNumber;
    // End of variables declaration//GEN-END:variables
}
