/* 
 * Copyright 2018 Cafe Sati Polska.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package Frames.Panels;

import GreenCoffeeClasses.CoffeeAttribute;
import GreenCoffeeClasses.CoffeeCountry;
import GreenCoffeeClasses.CoffeeGreen;
import GreenCoffeeClasses.CoffeeOwner;
import ProductionManagement.LabTest;
import GreenCoffeeClasses.CoffeeType;
import ProductionManagement.DataBaseConnector;
import ProductionManagement.Employee;
import GreenCoffeeClasses.PackType;
import GreenCoffeeClasses.Provider;
import ProductionManagement.Global;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.Arrays;
import javax.swing.ComboBoxModel;
import javax.swing.DefaultComboBoxModel;
import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Przemysław
 */
public class AddGreenCoffeePanel extends javax.swing.JPanel {

    /**
     * Creates new form AddGreenCoffeeMagazynierPanel
     */
    ArrayList<CoffeeType> alct;
    ArrayList<CoffeeOwner> alco;
    ArrayList<CoffeeCountry> alcc;
    ArrayList<PackType> alpt;
    ArrayList<Provider> alp;
    Employee emp;
    DataBaseConnector dbc = null;

    private void resetInput() {

        checkBoxVermin.setSelected(false);
        comboBoxCoffeeOwner.setSelectedItem(null);
        comboBoxCoffeeType.setSelectedItem(null);
        comboBoxPackType.setSelectedItem(null);
        comboBoxProvider.setSelectedItem(null);
        textFieldContractNumber.setText("");
        textFieldDossierNumber.setText("");
        spinnerPacksNumber.setValue(0);
        spinnerCoffeeWeight.setValue((float) 0);

    }

    private void loadTypes() {
        alct = dbc.getCoffeeType();

        Object[] o = alct.toArray();
        Arrays.sort(o);

        comboBoxCoffeeType.removeAllItems();
        for (Object ob : o) {
            CoffeeType ct = (CoffeeType) ob;
            comboBoxCoffeeType.addItem(ct);
        }
        comboBoxCoffeeType.setSelectedItem(null);
    }

    public AddGreenCoffeePanel(Employee emp) {
        initComponents();

        this.emp = emp;
        if (dbc == null) {
            dbc = Global.getDataBaseConnector();
        }
        dbc.clearSession();
        dbc.openSession();

        loadTypes();

        alco = dbc.getCoffeeOwner();
        comboBoxCoffeeOwner.removeAllItems();
        for (CoffeeOwner co : alco) {
            comboBoxCoffeeOwner.addItem(co);
        }
        comboBoxCoffeeOwner.setSelectedItem(null);

        alpt = dbc.getPackType();
        comboBoxPackType.removeAllItems();
        for (PackType pt : alpt) {
            comboBoxPackType.addItem(pt);
        }
        comboBoxPackType.setSelectedItem(null);

        alp = dbc.getProvider();
        Object[] o = alp.toArray();
        Arrays.sort(o);

        comboBoxProvider.removeAllItems();
        for (Object ob : o) {
            comboBoxProvider.addItem(ob);
        }
        comboBoxProvider.setSelectedItem(null);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        labelMain = new javax.swing.JLabel();
        labelCoffeOwner = new javax.swing.JLabel();
        comboBoxCoffeeOwner = new javax.swing.JComboBox();
        comboBoxPackType = new javax.swing.JComboBox();
        labelPackType = new javax.swing.JLabel();
        labelNumberOfPacks = new javax.swing.JLabel();
        labelCoffeeDossierNumber = new javax.swing.JLabel();
        labelContractNumber = new javax.swing.JLabel();
        textFieldContractNumber = new javax.swing.JTextField();
        labelWeight = new javax.swing.JLabel();
        buttonRegisterToLaboratory = new javax.swing.JButton();
        textFieldDossierNumber = new javax.swing.JTextField();
        labelCoffeOwner1 = new javax.swing.JLabel();
        comboBoxCoffeeType = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        comboBoxProvider = new javax.swing.JComboBox();
        checkBoxVermin = new javax.swing.JCheckBox();
        buttonAddNewCoffeeType = new javax.swing.JButton();
        buttonAddNewCoffeeOwner = new javax.swing.JButton();
        buttonAddNewCoffeeProvider = new javax.swing.JButton();
        buttonAddNewPackType = new javax.swing.JButton();
        spinnerCoffeeWeight = new javax.swing.JSpinner(new SpinnerNumberModel(new Float(0), new Float(0),null,new Float(0.01)))
        ;
        spinnerPacksNumber = new javax.swing.JSpinner();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();

        button1.setLabel("button1");

        labelMain.setText("Rejestrowanie kawy do badania");

        labelCoffeOwner.setText("Właściciel Kawy");

        labelPackType.setText("Rodzaj Pakownia");

        labelNumberOfPacks.setText("Ilość Opakowań");

        labelCoffeeDossierNumber.setText("Dossier");

        labelContractNumber.setText("Numer Kontraktu");

        labelWeight.setText("Waga [Kg]");

        buttonRegisterToLaboratory.setText("Zarejestruj do badania");
        buttonRegisterToLaboratory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterToLaboratoryActionPerformed(evt);
            }
        });

        labelCoffeOwner1.setText("Typ kawy");

        jLabel1.setText("Producent");

        checkBoxVermin.setText("Szkodniki obecne");

        buttonAddNewCoffeeType.setText("+");
        buttonAddNewCoffeeType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddNewCoffeeTypeActionPerformed(evt);
            }
        });

        buttonAddNewCoffeeOwner.setText("+");
        buttonAddNewCoffeeOwner.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddNewCoffeeOwnerActionPerformed(evt);
            }
        });

        buttonAddNewCoffeeProvider.setText("+");
        buttonAddNewCoffeeProvider.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddNewCoffeeProviderActionPerformed(evt);
            }
        });

        buttonAddNewPackType.setText("+");
        buttonAddNewPackType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddNewPackTypeActionPerformed(evt);
            }
        });

        spinnerCoffeeWeight.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), null, Float.valueOf(1.0f)));

        spinnerPacksNumber.setModel(new javax.swing.SpinnerNumberModel(Integer.valueOf(0), Integer.valueOf(0), null, Integer.valueOf(1)));

        jButton1.setText("Wyczyść");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("#");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Filtr");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Reset");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelMain)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelCoffeOwner1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCoffeOwner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNumberOfPacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCoffeeDossierNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelContractNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldContractNumber)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboBoxCoffeeOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonAddNewCoffeeOwner))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboBoxCoffeeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jButton4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonAddNewCoffeeType))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(comboBoxProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(buttonAddNewCoffeeProvider))))
                            .addComponent(textFieldDossierNumber)
                            .addComponent(spinnerPacksNumber)))
                    .addComponent(checkBoxVermin)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonRegisterToLaboratory)
                        .addGap(46, 46, 46)
                        .addComponent(jButton1))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPackType, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxPackType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(buttonAddNewPackType))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerCoffeeWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2)))
                .addContainerGap(164, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelMain)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxCoffeeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCoffeOwner1)
                    .addComponent(buttonAddNewCoffeeType)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jButton3)
                        .addComponent(jButton4)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxCoffeeOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCoffeOwner)
                    .addComponent(buttonAddNewCoffeeOwner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1)
                    .addComponent(buttonAddNewCoffeeProvider))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCoffeeDossierNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDossierNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContractNumber)
                    .addComponent(textFieldContractNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPackType)
                    .addComponent(comboBoxPackType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddNewPackType))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumberOfPacks)
                    .addComponent(spinnerPacksNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWeight)
                    .addComponent(spinnerCoffeeWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton2))
                .addGap(27, 27, 27)
                .addComponent(checkBoxVermin)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonRegisterToLaboratory)
                    .addComponent(jButton1))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegisterToLaboratoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterToLaboratoryActionPerformed
        // TODO add your handling code here:
        try {
            dbc.openSession();
            dbc.startTransation();
            String str = dbc.getMaxLabIdCoffeeGreen();
            String newLabIdStr;
            if (str != null) {
                Integer lastLabId = Integer.parseInt(str.substring(1, 7));
                newLabIdStr = String.format("K%06d", lastLabId + 1);
            } else {
                newLabIdStr = String.format("K%06d", 1);
            }

            CoffeeOwner coffeeOwner = (CoffeeOwner) comboBoxCoffeeOwner.getSelectedItem();
            String contractNumber = textFieldContractNumber.getText();
            CoffeeType coffeeType = (CoffeeType) comboBoxCoffeeType.getSelectedItem();
            String dossierNumber = textFieldDossierNumber.getText();
            Float weight = Global.round((Float) spinnerCoffeeWeight.getValue(), 2);
            Employee storeman = emp;
            PackType packType = (PackType) comboBoxPackType.getSelectedItem();
            String labId = newLabIdStr;
            Integer numberOfPacks = (Integer) spinnerPacksNumber.getValue();
            Provider provider = (Provider) comboBoxProvider.getSelectedItem();

            LabTest labTest = new LabTest();
            labTest.setVermin(checkBoxVermin.isSelected());
            dbc.saveTransation(labTest);
            CoffeeGreen cg = new CoffeeGreen(coffeeOwner, contractNumber, coffeeType, dossierNumber, weight, storeman, packType, labId, labTest, provider, numberOfPacks);
            dbc.saveTransation(cg);
            JOptionPane.showMessageDialog(null, "Zarejestrowano do badania.", "Informacja", JOptionPane.INFORMATION_MESSAGE);
            dbc.commitTransation();
        } catch (NumberFormatException | HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Sprawdź wprowadzone dane", "Błąd", JOptionPane.ERROR_MESSAGE);
            dbc.rollbackTransation();
        }
    }//GEN-LAST:event_buttonRegisterToLaboratoryActionPerformed

    private void buttonAddNewCoffeeTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddNewCoffeeTypeActionPerformed
        String[] option = {"Cofnij"};
        JOptionPane.showOptionDialog(this, new AddGreenCoffeeTypePanel(), "Dodaj nowy typ kawy", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE, null, option, option[0]);
        dbc.openSession();
        dbc.clearSession();
        alct = dbc.getCoffeeType();
        Object[] o = alct.toArray();
        Arrays.sort(o);
        comboBoxCoffeeType.removeAllItems();
        for (Object ob : o) {
            CoffeeType ct = (CoffeeType) ob;
            comboBoxCoffeeType.addItem(ct);
        }
        comboBoxCoffeeType.setSelectedItem(null);
    }//GEN-LAST:event_buttonAddNewCoffeeTypeActionPerformed

    private void buttonAddNewCoffeeOwnerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddNewCoffeeOwnerActionPerformed
        String[] option = {"Cofnij"};
        int result = JOptionPane.showOptionDialog(this, new AddCoffeeOwnerPanel(), "Dodaj nowego właściciela kawy", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE, null, option, option[0]);
        if (JOptionPane.OK_OPTION == result) {
            dbc.openSession();
            dbc.clearSession();
            alco = dbc.getCoffeeOwner();
            comboBoxCoffeeOwner.removeAllItems();
            for (CoffeeOwner co : alco) {
                comboBoxCoffeeOwner.addItem(co);
            }
            comboBoxCoffeeOwner.setSelectedItem(null);
        }
    }//GEN-LAST:event_buttonAddNewCoffeeOwnerActionPerformed

    private void buttonAddNewCoffeeProviderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddNewCoffeeProviderActionPerformed
        String[] option = {"Cofnij"};
        int result = JOptionPane.showOptionDialog(this, new AddProviderPanel(), "Dodaj nowego dostawcę", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE, null, option, option[0]);
        if (JOptionPane.OK_OPTION == result) {
            dbc.openSession();
            dbc.clearSession();
            alp = dbc.getProvider();
            Object[] o = alp.toArray();
            Arrays.sort(o);
            comboBoxProvider.removeAllItems();
            for (Object ob : o) {
                comboBoxProvider.addItem(ob);
            }
            comboBoxProvider.setSelectedItem(null);
        }
    }//GEN-LAST:event_buttonAddNewCoffeeProviderActionPerformed

    private void buttonAddNewPackTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddNewPackTypeActionPerformed
        String[] option = {"Cofnij"};
        int result = JOptionPane.showOptionDialog(this, new AddPackTypePanel(), "Dodaj nowy typ paczki", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE, null, option, option[0]);
        if (JOptionPane.OK_OPTION == result) {
            dbc.openSession();
            dbc.clearSession();
            alpt = dbc.getPackType();
            comboBoxPackType.removeAllItems();
            for (PackType pt : alpt) {
                comboBoxPackType.addItem(pt);
            }
            comboBoxPackType.setSelectedItem(null);
        }
    }//GEN-LAST:event_buttonAddNewPackTypeActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        resetInput();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        spinnerCoffeeWeight.setValue((float) (Integer) spinnerPacksNumber.getValue() * ((PackType) comboBoxPackType.getSelectedItem()).getSize());
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        BuildGreenCoffeeFilterPanel bgcfp = new BuildGreenCoffeeFilterPanel();
        String[] option = {"OK"};
        int result = JOptionPane.showOptionDialog(this, bgcfp, "Wbierz atrybuty", JOptionPane.OK_OPTION, JOptionPane.PLAIN_MESSAGE, null, option, option[0]);
        if (result == JOptionPane.OK_OPTION) {
            ArrayList<CoffeeAttribute> attributes = bgcfp.getAttributes();
            ComboBoxModel t = (ComboBoxModel) comboBoxCoffeeType.getModel();
            DefaultComboBoxModel dcbm = new DefaultComboBoxModel();
            for (int i = 0; i < t.getSize(); i++) {
                dcbm.addElement(t.getElementAt(i));
                for (CoffeeAttribute ca : attributes) {
                    if (t.getElementAt(i).toString().contains(ca.getShortcut())) {
                    } else {
                        dcbm.removeElement(t.getElementAt(i));
                        break;
                    }
                }
            }
            comboBoxCoffeeType.setModel(dcbm);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        loadTypes();
    }//GEN-LAST:event_jButton4ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JButton buttonAddNewCoffeeOwner;
    private javax.swing.JButton buttonAddNewCoffeeProvider;
    private javax.swing.JButton buttonAddNewCoffeeType;
    private javax.swing.JButton buttonAddNewPackType;
    private javax.swing.JButton buttonRegisterToLaboratory;
    private javax.swing.JCheckBox checkBoxVermin;
    private javax.swing.JComboBox comboBoxCoffeeOwner;
    private javax.swing.JComboBox comboBoxCoffeeType;
    private javax.swing.JComboBox comboBoxPackType;
    private javax.swing.JComboBox comboBoxProvider;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCoffeOwner;
    private javax.swing.JLabel labelCoffeOwner1;
    private javax.swing.JLabel labelCoffeeDossierNumber;
    private javax.swing.JLabel labelContractNumber;
    private javax.swing.JLabel labelMain;
    private javax.swing.JLabel labelNumberOfPacks;
    private javax.swing.JLabel labelPackType;
    private javax.swing.JLabel labelWeight;
    private javax.swing.JSpinner spinnerCoffeeWeight;
    private javax.swing.JSpinner spinnerPacksNumber;
    private javax.swing.JTextField textFieldContractNumber;
    private javax.swing.JTextField textFieldDossierNumber;
    // End of variables declaration//GEN-END:variables
}
