/* 
 * Copyright 2018 Cafe Sati Polska.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package Frames.Panels;

import ProductionClasses.ProductionLine;
import ProductionManagement.DataBaseConnector;
import ProductionManagement.Employee;
import ProductionManagement.Global;
import java.sql.Timestamp;
import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Przemysław
 */
public class AddNewEmployeePanel extends javax.swing.JPanel {

    DataBaseConnector dbc;

    /**
     * Creates new form AddNewEmployeePanel
     */
    private void resetInput() {

        comboBoxEmployeeJobPosition.setSelectedItem(null);

        textFieldEmployeeFirstName.setText("");
        textFieldEmployeeID.setText("");
        textFieldEmployeeLastName.setText("");
        textFieldEmployeeLogin.setText("");
        textFieldEmployeePassword.setText("");
        textFieldEmployeeRFID.setText("");

    }

    public AddNewEmployeePanel() {
        initComponents();
        if (dbc == null) {
            dbc = Global.getDataBaseConnector();
            dbc.openSession();
            dbc.clearSession();

        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldEmployeeFirstName = new javax.swing.JTextField();
        textFieldEmployeeLastName = new javax.swing.JTextField();
        textFieldEmployeeLogin = new javax.swing.JTextField();
        textFieldEmployeeRFID = new javax.swing.JFormattedTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        textFieldEmployeePassword = new javax.swing.JPasswordField();
        comboBoxEmployeeJobPosition = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        buttonAddEmployee = new javax.swing.JButton();
        textFieldEmployeeID = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();

        try {
            textFieldEmployeeRFID.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###.###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jLabel1.setText("Imię");

        jLabel2.setText("Nazwisko");

        jLabel3.setText("Login");

        jLabel4.setText("Hasło");

        comboBoxEmployeeJobPosition.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Magazynier", "Operator", "Kierownik Produkcji", "Laborant" }));

        jLabel5.setText("Stanowisko");

        jLabel6.setText("RFID");

        buttonAddEmployee.setText("Dodaj");
        buttonAddEmployee.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddEmployeeActionPerformed(evt);
            }
        });

        jLabel7.setText("ID pracownika/operatora");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(textFieldEmployeeFirstName, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                                .addComponent(textFieldEmployeeLogin))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(textFieldEmployeeRFID, javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(comboBoxEmployeeJobPosition, javax.swing.GroupLayout.Alignment.LEADING, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2)
                            .addComponent(jLabel4)
                            .addComponent(textFieldEmployeeLastName, javax.swing.GroupLayout.DEFAULT_SIZE, 151, Short.MAX_VALUE)
                            .addComponent(textFieldEmployeePassword)
                            .addComponent(jLabel7)
                            .addComponent(textFieldEmployeeID)))
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)
                    .addComponent(buttonAddEmployee))
                .addContainerGap(49, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldEmployeeFirstName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldEmployeeLastName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldEmployeeLogin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldEmployeePassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxEmployeeJobPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldEmployeeID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jLabel6)
                .addGap(5, 5, 5)
                .addComponent(textFieldEmployeeRFID, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(49, 49, 49)
                .addComponent(buttonAddEmployee)
                .addContainerGap(19, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddEmployeeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddEmployeeActionPerformed
        Employee e = new Employee();

        try {
            dbc.openSession();
            e.setFirstName(textFieldEmployeeFirstName.getText());
            e.setLastName(textFieldEmployeeLastName.getText());
            e.setLogin(textFieldEmployeeLogin.getText());
            e.setPassword(String.valueOf(textFieldEmployeePassword.getPassword()));
            e.setRfid(textFieldEmployeeRFID.getText());
            e.setJobPosition(comboBoxEmployeeJobPosition.getSelectedIndex() + 2);
            e.setRegDate(new Timestamp(System.currentTimeMillis()));
            e.setEmployeeID(textFieldEmployeeID.getText());

            if (dbc.getUserWithLogin(e.getLogin()) != null) {
                throw new UserLoginUsedException();
            }
            dbc.saveObject(e);

        } catch (UserLoginUsedException ex) {
            JOptionPane.showMessageDialog(null, "Uzytkownik o takim loginie już istnieje", "Błąd", JOptionPane.ERROR_MESSAGE);

        }
        resetInput();

    }//GEN-LAST:event_buttonAddEmployeeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddEmployee;
    private javax.swing.JComboBox comboBoxEmployeeJobPosition;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JTextField textFieldEmployeeFirstName;
    private javax.swing.JTextField textFieldEmployeeID;
    private javax.swing.JTextField textFieldEmployeeLastName;
    private javax.swing.JTextField textFieldEmployeeLogin;
    private javax.swing.JPasswordField textFieldEmployeePassword;
    private javax.swing.JFormattedTextField textFieldEmployeeRFID;
    // End of variables declaration//GEN-END:variables

    private static class UserLoginUsedException extends Exception {

        public UserLoginUsedException() {
        }
    }
}
