/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Frames.Panels;

import ProductionClasses.ProductionLine;
import ProductionManagement.DataBaseConnector;
import ProductionManagement.Global;
import javax.swing.JOptionPane;

/**
 *
 * @author Przemysław
 */
public class AddProductionLinePanel extends javax.swing.JPanel {

    DataBaseConnector dbc = null;

    /**
     * Creates new form AddProductAdministratorFrame
     */
    public AddProductionLinePanel() {
        initComponents();
        if (dbc == null) {
            dbc = Global.getDataBaseConnector();
            dbc.clearSession();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldProductionPosition = new javax.swing.JTextField();
        buttonAddProductionPosition = new javax.swing.JButton();
        jCheckBox1 = new javax.swing.JCheckBox();

        jLabel1.setText("Nazwa lini produkcyjnej");

        buttonAddProductionPosition.setText("Dodaj");
        buttonAddProductionPosition.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddProductionPositionActionPerformed(evt);
            }
        });

        jCheckBox1.setText("Linia przeznaczona do wypalania kawy");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox1)
                    .addComponent(jLabel1)
                    .addComponent(textFieldProductionPosition, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddProductionPosition))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldProductionPosition, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jCheckBox1)
                .addGap(39, 39, 39)
                .addComponent(buttonAddProductionPosition)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddProductionPositionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddProductionPositionActionPerformed
        dbc.openSession();

        ProductionLine pl = new ProductionLine();
        pl.setLine(textFieldProductionPosition.getText());

        pl.setRoast(jCheckBox1.isSelected());
        dbc.saveObject(pl);
        dbc.closeSession();
        JOptionPane.showMessageDialog(null, "Dodano nowy element", "Informacja", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_buttonAddProductionPositionActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddProductionPosition;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField textFieldProductionPosition;
    // End of variables declaration//GEN-END:variables
}
