/* 
 * Copyright 2018 Cafe Sati Polska.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package Frames.Panels;

import ProductClasses.ProductDestination;
import ProductClasses.ProductType;
import ProductionManagement.DataBaseConnector;
import ProductionManagement.Global;
import java.awt.event.ItemEvent;
import java.awt.event.ItemListener;
import java.io.File;
import java.sql.Timestamp;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Przemysław
 */
public class AddProductTypePanel extends javax.swing.JPanel {

    DataBaseConnector dbc = null;

    String fileURL = null;
    String fileURLInstant = null;
    boolean instant = false;
    String labelFileURLInitValue = "Adres wybranej karty produktu";
    String labelFileURLInstantInitValue = "Adres wybranej karty mieszania";

    /**
     * Creates new form AddProductAdministratorFrame
     */
    public AddProductTypePanel() {
        initComponents();
        buttonMixFile.setEnabled(false);
        buttonProductFile.setEnabled(false);
        labelMixFileURL.setText(labelFileURLInstantInitValue);
        labelProductFileURL.setText(labelFileURLInitValue);
        checkBoxInstant.setEnabled(false);
        comboBoxProductType.addItemListener(new ItemListener() {

            public void itemStateChanged(ItemEvent e) {
                if (comboBoxProductType.getSelectedIndex() == 0) {
                    checkBoxInstant.setSelected(false);
                    checkBoxInstant.setEnabled(false);
                } else {
                    checkBoxInstant.setEnabled(true);
                }
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonAddProduct = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textFieldProductName = new javax.swing.JTextField();
        checkBoxInstant = new javax.swing.JCheckBox();
        buttonProductFile = new javax.swing.JButton();
        buttonMixFile = new javax.swing.JButton();
        labelProductFileURL = new javax.swing.JLabel();
        labelMixFileURL = new javax.swing.JLabel();
        comboBoxProductType = new javax.swing.JComboBox();
        textFieldEAN = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();

        buttonAddProduct.setText("Dodaj produkt");
        buttonAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddProductActionPerformed(evt);
            }
        });

        jLabel1.setText("Nazwa Produktu");

        checkBoxInstant.setText("Produkt typu instant");
        checkBoxInstant.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                checkBoxInstantStateChanged(evt);
            }
        });

        buttonProductFile.setText("Dodaj kartę produktu");
        buttonProductFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProductFileActionPerformed(evt);
            }
        });

        buttonMixFile.setText("Dodaj kartę mieszania");
        buttonMixFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMixFileActionPerformed(evt);
            }
        });

        labelProductFileURL.setText("Adres karty produktu:  ");

        labelMixFileURL.setText("Adres karty mieszania: ");

        comboBoxProductType.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Palenie", "Pakowanie" }));

        textFieldEAN.setColumns(13);
        textFieldEAN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldEANActionPerformed(evt);
            }
        });

        jLabel2.setText("EAN13");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldProductName))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(buttonAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(buttonProductFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonMixFile))
                            .addComponent(labelProductFileURL)
                            .addComponent(labelMixFileURL)
                            .addComponent(checkBoxInstant)
                            .addComponent(comboBoxProductType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(textFieldEAN)))
                        .addGap(0, 335, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(comboBoxProductType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxInstant)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonProductFile)
                    .addComponent(buttonMixFile))
                .addGap(1, 1, 1)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(textFieldEAN, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelProductFileURL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMixFileURL)
                .addGap(40, 40, 40)
                .addComponent(buttonAddProduct)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddProductActionPerformed
        ProductType ptf = new ProductType();
        if (dbc == null) {
            dbc = Global.getDataBaseConnector();
        }
        try {
            dbc.openSession();
            ptf.setProductName(textFieldProductName.getText());
            ptf.setVersion(1);
            ptf.setFileURL(fileURL);
            ptf.setType(comboBoxProductType.getSelectedIndex() + 1);
            ptf.setHidden(false);
            ptf.setEan(textFieldEAN.getText());
            if (instant) {
                ptf.setInstant(instant);
                ptf.setFileURLinstant(fileURLInstant);
            }
            ptf.setCreateDate(new Timestamp(System.currentTimeMillis()));
            dbc.saveObject(ptf);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Wybierz plik z kartą palnienia produktu");
        } catch (Exception e) {
            System.out.println(e.getStackTrace().toString());
            System.out.println(e.toString());
        } finally {
            JOptionPane.showMessageDialog(null, "Dodano nowy produkt.", "Informacja", JOptionPane.INFORMATION_MESSAGE);
            System.out.println(ptf.getFileURL());
        }

    }//GEN-LAST:event_buttonAddProductActionPerformed

    private void buttonProductFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProductFileActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("\\\\192.168.17.10\\public"));
        fileChooser.showOpenDialog(this);
        fileURL = fileChooser.getSelectedFile().getAbsolutePath();
        if (fileURL != null) {
            labelProductFileURL.setText(labelFileURLInitValue + fileURL);
            JOptionPane.showMessageDialog(this, "Wybrano plik" + System.lineSeparator() + fileURL);
        } else {
            JOptionPane.showMessageDialog(this, "Proszę ponownie wybrać plik");
        }


    }//GEN-LAST:event_buttonProductFileActionPerformed

    private void checkBoxInstantStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_checkBoxInstantStateChanged
        instant = checkBoxInstant.isSelected();
        if (instant) {
            buttonMixFile.setEnabled(true);
            buttonProductFile.setEnabled(true);
        } else {
            labelMixFileURL.setText("Wybrany produkt nie jest typu instant.");
            buttonMixFile.setEnabled(false);
            buttonProductFile.setEnabled(true);

        }
    }//GEN-LAST:event_checkBoxInstantStateChanged

    private void buttonMixFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMixFileActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("\\\\192.168.17.10\\public"));
        fileChooser.showOpenDialog(this);

        fileURLInstant = fileChooser.getSelectedFile().getAbsolutePath();
        if (fileURLInstant != null) {
            labelMixFileURL.setText(labelFileURLInstantInitValue + fileURLInstant);
            JOptionPane.showMessageDialog(this, "Wybrano plik" + System.lineSeparator() + fileURLInstant);
        } else {
            JOptionPane.showMessageDialog(this, "Proszę ponownie wybrać plik");
        }
    }//GEN-LAST:event_buttonMixFileActionPerformed

    private void textFieldEANActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldEANActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldEANActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddProduct;
    private javax.swing.JButton buttonMixFile;
    private javax.swing.JButton buttonProductFile;
    private javax.swing.JCheckBox checkBoxInstant;
    private javax.swing.JComboBox comboBoxProductType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel labelMixFileURL;
    private javax.swing.JLabel labelProductFileURL;
    private javax.swing.JTextField textFieldEAN;
    private javax.swing.JTextField textFieldProductName;
    // End of variables declaration//GEN-END:variables
}
