/* 
 * Copyright 2018 Cafe Sati Polska.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package Frames.Panels;

import ProductClasses.ReturnedProduct;
import ProductionClasses.ProductionCoffee;
import ProductionClasses.ProductionCoffeeExternalReturn;
import ProductionClasses.ProductionRaportPart;
import ProductionManagement.DataBaseConnector;
import ProductionManagement.Employee;
import ProductionManagement.Global;
import ProductionManagement.LabTest;
import java.sql.Timestamp;
import javax.swing.JOptionPane;

/**
 *
 * @author Przemysław
 */
public class AddReturnedProductPanel extends javax.swing.JPanel {
    
    ProductionRaportPart selectedProductionRaportPart;
    Employee emp;
    DataBaseConnector dbc;

    /**
     * Creates new form AddReturnedCoffeePanel
     */
    public AddReturnedProductPanel(Employee e) {
        initComponents();
        emp = e;
        if (dbc == null) {
            dbc = Global.getDataBaseConnector();
            dbc.clearSession();
        }
    }
    
    private void resetInput() {
        selectedProductionRaportPart = null;
        labelProductionRaportPart.setText("");
        jSpinner1.setValue(new Float(0));
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonFind = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        labelProductionRaportPart = new javax.swing.JLabel();
        jSpinner1 = new javax.swing.JSpinner();
        jLabel2 = new javax.swing.JLabel();
        buttonSendToHall = new javax.swing.JButton();

        buttonFind.setText("Przeszukaj raporty produkcji");
        buttonFind.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFindActionPerformed(evt);
            }
        });

        jLabel1.setText("Produkcja przekazana do pakownia.");

        jSpinner1.setModel(new javax.swing.SpinnerNumberModel(Float.valueOf(0.0f), Float.valueOf(0.0f), null, Float.valueOf(0.1f)));

        jLabel2.setText("Ilość wydanej kawy");

        buttonSendToHall.setText("Wydaj");
        buttonSendToHall.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonSendToHallActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelProductionRaportPart, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(buttonFind)
                            .addComponent(jLabel1)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(buttonSendToHall))
                        .addGap(0, 8, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(buttonFind)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(10, 10, 10)
                .addComponent(labelProductionRaportPart, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(35, 35, 35)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jSpinner1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(buttonSendToHall)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFindActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFindActionPerformed
        BrowseProductionRaportPartPanel bprp = new BrowseProductionRaportPartPanel();
        String[] options = {"Zamknij"};
        int result = JOptionPane.showOptionDialog(null, bprp, "Wybierz raport produkcji.", JOptionPane.YES_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
        if (JOptionPane.OK_OPTION == result) {
            selectedProductionRaportPart = bprp.getSelectedProductionRaportPart();
            if (selectedProductionRaportPart == null) {
                labelProductionRaportPart.setText("Nie wybrano raportu.");
            } else {
                labelProductionRaportPart.setText(selectedProductionRaportPart.toString());
            }
        }
    }//GEN-LAST:event_buttonFindActionPerformed

    private void buttonSendToHallActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonSendToHallActionPerformed
        dbc.openSession();
        
        ReturnedProduct rp = new ReturnedProduct();
        ProductionCoffee pc = new ProductionCoffee();
        pc.setProductType(selectedProductionRaportPart.getProductType());
        pc.setReturned(false);
        pc.setState(Global.PRODUCTION_COFFEE_READY);
        pc.setWeight(Global.round((Float) jSpinner1.getValue(), 2));
        pc.setProdDate(new Timestamp(System.currentTimeMillis()));
        rp.setProductionRaportPart(selectedProductionRaportPart);
        rp.setProductionCoffee(pc);
        
        dbc.saveObject(pc);
        dbc.saveObject(rp);
        
        JOptionPane.showMessageDialog(null, "Wydano na produkcję.", "Informacja", JOptionPane.INFORMATION_MESSAGE);
        resetInput();
        

    }//GEN-LAST:event_buttonSendToHallActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonFind;
    private javax.swing.JButton buttonSendToHall;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSpinner jSpinner1;
    private javax.swing.JLabel labelProductionRaportPart;
    // End of variables declaration//GEN-END:variables
}
