/* 
 * Copyright 2018 Cafe Sati Polska.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package Frames.Panels;

import ProductClasses.SugarType;
import ProductionManagement.DataBaseConnector;
import ProductionManagement.Global;
import javax.swing.JOptionPane;

/**
 *
 * @author Przemysław
 */
public class AddSugarTypePanel extends javax.swing.JPanel {

    DataBaseConnector dbc = null;

    /**
     * Creates new form AddAromaTypePanel
     */
    private void resetInput() {
        textFieldSugarType.setText("");
    }

    public AddSugarTypePanel() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        textFieldSugarType = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        buttonAddNewSugarType = new javax.swing.JButton();

        textFieldSugarType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                textFieldSugarTypeActionPerformed(evt);
            }
        });

        jLabel1.setText("Nazwa cukru");

        jLabel3.setText("Dodawanie nowego typu cukru");

        buttonAddNewSugarType.setText("Dodaj");
        buttonAddNewSugarType.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddNewSugarTypeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldSugarType, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(buttonAddNewSugarType, javax.swing.GroupLayout.Alignment.TRAILING))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(textFieldSugarType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonAddNewSugarType)
                .addContainerGap(60, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddNewSugarTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddNewSugarTypeActionPerformed
        SugarType newSugarType = new SugarType();
        if (dbc == null) {
            dbc = Global.getDataBaseConnector();
            dbc.openSession();
        }
        newSugarType.setType(textFieldSugarType.getText());
        dbc.saveObject(newSugarType);
        JOptionPane.showMessageDialog(null, "Dodano nowy element", "Informacja", JOptionPane.INFORMATION_MESSAGE);
        resetInput();
    }//GEN-LAST:event_buttonAddNewSugarTypeActionPerformed

    private void textFieldSugarTypeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_textFieldSugarTypeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_textFieldSugarTypeActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddNewSugarType;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField textFieldSugarType;
    // End of variables declaration//GEN-END:variables
}
