/* 
 * Copyright 2018 Cafe Sati Polska.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package Frames.Panels;

import GreenCoffeeClasses.CoffeeGreen;
import ProductionManagement.Global;
import javax.print.DocFlavor;
import javax.print.PrintService;
import javax.print.PrintServiceLookup;
import javax.swing.JOptionPane;
import javax.swing.JTextArea;

/**
 *
 * @author Przemysław
 */
public class DetailsGreenCoffeePanel extends javax.swing.JPanel {

    /**
     * Creates new form GreenCoffeeDetailsPanel
     */
    private final CoffeeGreen coffeeGreen;

    private void loadData() {
        textFieldArrivalWeight.setText(Float.toString(coffeeGreen.getArrivalWeight()));
        textFieldCoffeeName.setText(coffeeGreen.getCoffeeType().toString());
        textFieldContractNumber.setText(coffeeGreen.getContractNumber());
        textFieldCurrentWeight.setText(Float.toString(coffeeGreen.getCurrentWeight()));
        textFieldDossier.setText(coffeeGreen.getDossierNumber());
        textFieldLabId.setText(coffeeGreen.getLabId());
        textFieldOwner.setText(coffeeGreen.getCoffeeOwner().toString());
        textFieldPackType.setText(coffeeGreen.getPackType().toString());
        textFieldProvider.setText(coffeeGreen.getProvider().toString());
        textFieldStoreman.setText(coffeeGreen.getStoreman().toString());
        textFieldArrivalDate.setText(coffeeGreen.getArrivalDate().toString());
    }

    public DetailsGreenCoffeePanel(CoffeeGreen cg) {
        initComponents();
        coffeeGreen = cg;
        loadData();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        buttonShowLabTest = new javax.swing.JButton();
        jLabel10 = new javax.swing.JLabel();
        textFieldCoffeeName = new javax.swing.JTextField();
        textFieldLabId = new javax.swing.JTextField();
        textFieldProvider = new javax.swing.JTextField();
        textFieldOwner = new javax.swing.JTextField();
        textFieldDossier = new javax.swing.JTextField();
        textFieldContractNumber = new javax.swing.JTextField();
        textFieldPackType = new javax.swing.JTextField();
        textFieldArrivalWeight = new javax.swing.JTextField();
        textFieldCurrentWeight = new javax.swing.JTextField();
        textFieldStoreman = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
        textFieldArrivalDate = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        buttonEdit2 = new javax.swing.JButton();

        jLabel1.setText("Nazwa kawy");

        jLabel2.setText("Numer zlecenia kontroli");

        jLabel3.setText("Producent");

        jLabel4.setText("Dossier");

        jLabel5.setText("Numer kontraktu");

        jLabel6.setText("Właściciel");

        jLabel7.setText("Typ opakowania");

        jLabel8.setText("Waga przy dostawie");

        jLabel9.setText("Aktualna waga");

        buttonShowLabTest.setText("Zobacz raport z badania");
        buttonShowLabTest.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonShowLabTestActionPerformed(evt);
            }
        });

        jLabel10.setText("Zmagazynował");

        textFieldCoffeeName.setText("jTextField1");

        textFieldLabId.setText("jTextField2");

        textFieldProvider.setText("jTextField3");

        textFieldOwner.setText("jTextField4");

        textFieldDossier.setText("jTextField5");

        textFieldContractNumber.setText("jTextField6");

        textFieldPackType.setText("jTextField7");

        textFieldArrivalWeight.setText("jTextField8");

        textFieldCurrentWeight.setText("jTextField9");

        textFieldStoreman.setText("jTextField11");

        jLabel11.setText("Data dostawy");

        textFieldArrivalDate.setText("jTextField1");

        jButton1.setText("Zobacz zmiany");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Drukuj");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        buttonEdit2.setText("Edytuj");
        buttonEdit2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonEdit2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel10)
                            .addComponent(jLabel11)
                            .addComponent(jLabel9)
                            .addComponent(jLabel8)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel5)
                            .addComponent(jLabel7))
                        .addGap(90, 90, 90)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(textFieldCoffeeName, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                                    .addComponent(textFieldProvider))
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addComponent(textFieldLabId)
                            .addComponent(textFieldArrivalWeight)
                            .addComponent(textFieldCurrentWeight)
                            .addComponent(textFieldStoreman, javax.swing.GroupLayout.DEFAULT_SIZE, 256, Short.MAX_VALUE)
                            .addComponent(textFieldArrivalDate)
                            .addComponent(textFieldPackType)
                            .addComponent(textFieldContractNumber)
                            .addComponent(textFieldDossier)
                            .addComponent(textFieldOwner, javax.swing.GroupLayout.Alignment.TRAILING)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonShowLabTest)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 112, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(buttonEdit2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldCoffeeName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldLabId, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textFieldProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(textFieldOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textFieldDossier, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(textFieldContractNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(textFieldPackType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(textFieldArrivalWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(textFieldCurrentWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(textFieldStoreman, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(textFieldArrivalDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonShowLabTest)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonEdit2)
                    .addComponent(jButton1))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonShowLabTestActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonShowLabTestActionPerformed
        if (coffeeGreen.getLabTest().getLabAssistant() != null) {
            coffeeGreen.getLabTest().showDetails();
        }
    }//GEN-LAST:event_buttonShowLabTestActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        String[] options = new String[]{"OK"};
        JOptionPane.showOptionDialog(null, new ShowResourceCoffeeChangeHistoryPanel(coffeeGreen.getCoffeeGreenChangeHistory()), "Podgląd zmian.", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            StringBuilder sb = new StringBuilder();

            sb.append("Szczegóły kawy zielonej ").append(coffeeGreen.toString()).append(System.lineSeparator()).append(System.lineSeparator());

            sb.append("    ").append("Numer zlecenia kontroli:  ").append(coffeeGreen.getLabId()).append(System.lineSeparator());
            sb.append("    ").append("Typ kawy:  ").append(coffeeGreen.getCoffeeType()).append(System.lineSeparator());
            sb.append("    ").append("Data dostawy:  ").append(Global.timestampToStrDDMMYYYY(coffeeGreen.getArrivalDate())).append(System.lineSeparator());
            sb.append("    ").append("Zmagazynował(a):  ").append(coffeeGreen.getStoreman().toString()).append(System.lineSeparator());
            sb.append("    ").append("Producent:  ").append(coffeeGreen.getProvider()).append(System.lineSeparator());
            sb.append("    ").append("Właściciel:  ").append(coffeeGreen.getCoffeeOwner()).append(System.lineSeparator());
            sb.append("    ").append("Dossier:  ").append(coffeeGreen.getDossierNumber()).append(System.lineSeparator());
            sb.append("    ").append("Typ opakowania:  ").append(coffeeGreen.getPackType()).append(System.lineSeparator());
            sb.append("    ").append("Ilość opakowań:  ").append(coffeeGreen.getNumberOfPacks()).append(System.lineSeparator());
            sb.append("    ").append("Waga podczas dostawy:  ").append(coffeeGreen.getArrivalWeight()).append(System.lineSeparator());
            sb.append("    ").append("Aktualna waga:  ").append(coffeeGreen.getCurrentWeight()).append(System.lineSeparator());

            sb.append("    ").append("Dane badania: ").append(System.lineSeparator());
            if (coffeeGreen.getLabTest().isAccepted()) {
                sb.append("    ").append("    ").append("Stan: ").append("ZATWIERDZONY").append(System.lineSeparator());
            } else {
                sb.append("    ").append("    ").append("Stan: ").append("ODRZUCONY").append(System.lineSeparator());
            }
            if (coffeeGreen.getLabTest().isVermin()) {
                sb.append("    ").append("    ").append("Szkodniki wykryte.").append(System.lineSeparator());
            } else {
                sb.append("    ").append("    ").append("Szkodniki nie wykryte.").append(System.lineSeparator());
            }
            sb.append("    ").append("    ").append("Wynik badania organoleptycznego: ").append(coffeeGreen.getLabTest().getOrganoleptic()).append(System.lineSeparator());
            sb.append("    ").append("    ").append("Wynik badania technicznego: ").append(coffeeGreen.getLabTest().getTechnical()).append(System.lineSeparator());
            sb.append("    ").append("    ").append("Data badania: ").append((Global.timestampToStrDDMMYYYY(coffeeGreen.getLabTest().getExamineDate()))).append(System.lineSeparator());
            sb.append("    ").append("    ").append("Badanie wykonał(a): ").append(coffeeGreen.getLabTest().getLabAssistant().toString()).append(System.lineSeparator()).append(System.lineSeparator());
            sb.append(coffeeGreen.getLabTest().getDetails());
            DocFlavor flavor = DocFlavor.INPUT_STREAM.AUTOSENSE;
            PrintService[] services = PrintServiceLookup.lookupPrintServices(flavor, null);
            PrintService defaultService = PrintServiceLookup.lookupDefaultPrintService();
            if (services.length != 0) {
                if (defaultService != null) {
                    JTextArea text = new JTextArea(sb.toString());
                    PrintService service = PrintServiceLookup.lookupDefaultPrintService();
                    text.print(null, null, false, service, null, false);
                }
            }
        } catch (Exception e) {
            e.printStackTrace();
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void buttonEdit2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonEdit2ActionPerformed
        if (Global.getEmployee().getJobPosition() == Global.ADMINISTRATOR
                || Global.getEmployee().getJobPosition() == Global.STOREMAN
                || Global.getEmployee().getJobPosition() == Global.OFFICE
                || Global.getEmployee().getJobPosition() == Global.LAB_ASSISTANT) {
            coffeeGreen.edit();
            loadData();
        } else {
            JOptionPane.showMessageDialog(null, "Brak uprawnień!", "Uwaga!", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonEdit2ActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonEdit2;
    private javax.swing.JButton buttonShowLabTest;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JTextField textFieldArrivalDate;
    private javax.swing.JTextField textFieldArrivalWeight;
    private javax.swing.JTextField textFieldCoffeeName;
    private javax.swing.JTextField textFieldContractNumber;
    private javax.swing.JTextField textFieldCurrentWeight;
    private javax.swing.JTextField textFieldDossier;
    private javax.swing.JTextField textFieldLabId;
    private javax.swing.JTextField textFieldOwner;
    private javax.swing.JTextField textFieldPackType;
    private javax.swing.JTextField textFieldProvider;
    private javax.swing.JTextField textFieldStoreman;
    // End of variables declaration//GEN-END:variables
}
