/* 
 * Copyright 2018 Cafe Sati Polska.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package Frames.Panels;

import ProductionManagement.Employee;
import ProductionManagement.Global;
import ProductionManagement.LabTest;
import SatiExtends.Test;
import java.awt.Color;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import javax.swing.JScrollPane;

/**
 *
 * @author Przemysław
 */
public class DetailsLabTestPanel extends javax.swing.JPanel {

    /**
     * Creates new form DetailsLabTestPanel
     */
    LabTest lt;

    public DetailsLabTestPanel(LabTest lt) {
        initComponents();
        this.lt = lt;
        Employee e = Global.getEmployee();
        if (e.getJobPosition() == Global.LAB_ASSISTANT || e.getJobPosition() == Global.OFFICE || e.getJobPosition() == Global.CEO || e.getJobPosition() == Global.ADMINISTRATOR) {
        } else {
            buttonMoreInfo.setEnabled(false);
            buttonMoreInfo.setVisible(false);
        }

        if (lt.isAccepted()) {
            labelState.setText("Zaakceptwano surowiec!");
            labelState.setForeground(Color.GREEN);
            //   labelState.setBackground(Color.BLACK);
        } else {
            labelState.setText("Odrzucono surowiec!");
            labelState.setForeground(Color.RED);
            //  labelState.setBackground(Color.BLACK);
        }
        textFieldLabAssistant.setText(lt.getLabAssistant().toString());
        textFieldLabTestDate.setText(lt.getExamineDate().toString());;
        textFieldOrganoleptic.setText(lt.getOrganoleptic());
        textFieldSampleSize.setText(Float.toString(lt.getSampleSize()));
        textFieldTechnical.setText(lt.getTechnical());
        if (lt.isVermin()) {
            textFieldVermin.setText("Zaobserwowano");
        } else {
            textFieldVermin.setText("Nie wykryto");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        textFieldLabAssistant = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        textFieldLabTestDate = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        textFieldVermin = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        textFieldSampleSize = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        textFieldOrganoleptic = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        textFieldTechnical = new javax.swing.JTextArea();
        labelState = new javax.swing.JLabel();
        buttonMoreInfo = new javax.swing.JButton();

        jLabel1.setText("Wykonał(a):");

        textFieldLabAssistant.setText("jTextField1");

        jLabel2.setText("Data badania: ");

        textFieldLabTestDate.setText("jTextField2");

        jLabel3.setText("Obecność szkodników: ");

        textFieldVermin.setText("jTextField3");

        jLabel4.setText("Wielkość próbki: ");

        textFieldSampleSize.setText("jTextField4");

        jLabel5.setText("Wynik badania ogranoleptycznego:");

        textFieldOrganoleptic.setColumns(20);
        textFieldOrganoleptic.setRows(5);
        jScrollPane1.setViewportView(textFieldOrganoleptic);

        jLabel6.setText("Wynik badania technicznego: ");

        textFieldTechnical.setColumns(20);
        textFieldTechnical.setRows(5);
        jScrollPane2.setViewportView(textFieldTechnical);

        labelState.setText("jLabel7");

        buttonMoreInfo.setText("Więcej");
        buttonMoreInfo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMoreInfoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jScrollPane1)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel2)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4)
                            .addComponent(labelState))
                        .addGap(53, 53, 53)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(textFieldLabAssistant, javax.swing.GroupLayout.DEFAULT_SIZE, 216, Short.MAX_VALUE)
                            .addComponent(textFieldLabTestDate)
                            .addComponent(textFieldVermin)
                            .addComponent(textFieldSampleSize)))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel6)
                            .addComponent(buttonMoreInfo))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(7, 7, 7)
                .addComponent(labelState)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(textFieldLabAssistant, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(textFieldLabTestDate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(textFieldVermin, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(textFieldSampleSize, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(buttonMoreInfo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonMoreInfoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMoreInfoActionPerformed
        String options[] = new String[]{"Zamknij"};
        switch (lt.getType()) {
            case (Global.RESOURCE_TYPE_COFFEE_GREEN):
                JOptionPane.showOptionDialog(this, new DetailsLabTestGreenCoffeePanel(lt, lt.getType()), "Uzupełnij dane badania", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
                break;
            case (Global.RESOURCE_TYPE_AROMA):
                JOptionPane.showOptionDialog(this, new DetailsLabTestAromaPanel(lt, lt.getType()), "Uzupełnij dane badania", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
                break;
            case (Global.RESOURCE_TYPE_CARDBOARD):
                JOptionPane.showOptionDialog(this, new DetailsLabTestCardboardPanel(lt, lt.getType()), "Uzupełnij dane badania", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
                break;
            case (Global.RESOURCE_TYPE_COFFEE_INSTANT):
                JScrollPane scrollPane = new JScrollPane(new DetailsLabTestInstantPanel(lt, lt.getType()));
                scrollPane.setPreferredSize(new Dimension(650, 550));
                JOptionPane.showOptionDialog(this, scrollPane, "Uzupełnij dane badania", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
                break;
            case (Global.RESOURCE_TYPE_COFFEE_OTHER):
                JOptionPane.showOptionDialog(this, new DetailsLabTestCoffeeOtherPanel(lt, lt.getType()), "Uzupełnij dane badania", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
                break;
            case (Global.RESOURCE_TYPE_COFFEE_POWDER):
                JOptionPane.showOptionDialog(this, new DetailsLabTestPowderPanel(lt, lt.getType()), "Uzupełnij dane badania", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
                break;
            case (Global.RESOURCE_TYPE_PACKAGE):
                JOptionPane.showOptionDialog(this, new DetailsLabTestPackagePanel(lt, lt.getType()), "Uzupełnij dane badania", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
                break;
            case (Global.RESOURCE_TYPE_COFFEE_PADS):
                JOptionPane.showOptionDialog(this, new DetailsLabTestCoffeePadsPanel(lt, lt.getType()), "Uzupełnij dane badania", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
                break;
            case (Global.RESOURCE_TYPE_COFFEE_RETURNED):
                JOptionPane.showOptionDialog(this, new DetailsLabTestCoffeeRetrunedPanel(lt, lt.getType()), "Uzupełnij dane badania", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
                break;
            case (Global.RESOURCE_TYPE_COFFEE_CAPSULE):
                JOptionPane.showOptionDialog(this, new DetailsLabTestCoffeeCapsulePanel(lt, lt.getType()), "Uzupełnij dane badania", JOptionPane.YES_NO_OPTION, JOptionPane.PLAIN_MESSAGE, null, options, options[0]);
                break;
        }
    }//GEN-LAST:event_buttonMoreInfoActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonMoreInfo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel labelState;
    private javax.swing.JTextField textFieldLabAssistant;
    private javax.swing.JTextField textFieldLabTestDate;
    private javax.swing.JTextArea textFieldOrganoleptic;
    private javax.swing.JTextField textFieldSampleSize;
    private javax.swing.JTextArea textFieldTechnical;
    private javax.swing.JTextField textFieldVermin;
    // End of variables declaration//GEN-END:variables
}
