/* 
 * Copyright 2018 Cafe Sati Polska.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package Frames.Panels;

import ProductClasses.ProductDestination;
import ProductClasses.ProductType;
import ProductionManagement.DataBaseConnector;
import ProductionManagement.Global;
import java.io.File;
import java.sql.Timestamp;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;

/**
 *
 * @author Przemysław
 */
public class EditProductTypeFilePanel extends javax.swing.JPanel {

    DataBaseConnector dbc = null;
    ArrayList<ProductDestination> alpd = null;
    ProductType ptf;

    String fileURL = null;

    String fileURLInstant = null;
    boolean hidden = false;
    boolean instant = false;
    String labelFileURLInitValue = "Adres wybranej karty produktu: ";
    String labelFileURLInstantInitValue = "Adres wybranej karty mieszania: ";

    /**
     * Creates new form AddProductAdministratorFrame
     */
    public EditProductTypeFilePanel(ProductType ptf) {

        initComponents();
        this.ptf = ptf;
        instant = ptf.isInstant();
        fileURL = ptf.getFileURL();
        hidden = ptf.isHidden();
        textFieldProductName.setText(ptf.getProductName());
        textFieldProductName.setEditable(false);
        labelProductFileURL.setText(labelFileURLInitValue + fileURL);
        checkBoxInstant.setSelected(instant);
        checkBoxInstant.setEnabled(false);
        if (instant) {
            fileURLInstant = ptf.getFileURLinstant();
            labelMixFileURL.setText(labelFileURLInstantInitValue + fileURLInstant);
        }
        if (!instant) {
            buttonMixFile.setEnabled(false);
            buttonMixFile.setVisible(false);
            labelMixFileURL.setVisible(false);
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        buttonAddProduct = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        textFieldProductName = new javax.swing.JTextField();
        checkBoxInstant = new javax.swing.JCheckBox();
        buttonProductFile = new javax.swing.JButton();
        buttonMixFile = new javax.swing.JButton();
        labelProductFileURL = new javax.swing.JLabel();
        labelMixFileURL = new javax.swing.JLabel();

        buttonAddProduct.setText("Dodaj nową wersję produktu");
        buttonAddProduct.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonAddProductActionPerformed(evt);
            }
        });

        jLabel1.setText("Nazwa Produktu");

        textFieldProductName.setText("Test");

        checkBoxInstant.setText("Produkt typu instant");

        buttonProductFile.setText("Zmień kartę produktu");
        buttonProductFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonProductFileActionPerformed(evt);
            }
        });

        buttonMixFile.setText("Zmień kartę mieszania");
        buttonMixFile.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonMixFileActionPerformed(evt);
            }
        });

        labelProductFileURL.setText("Adres karty produktu:  ");

        labelMixFileURL.setText("Adres karty mieszania: ");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(textFieldProductName))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(checkBoxInstant)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(buttonProductFile)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(buttonMixFile))
                            .addComponent(labelProductFileURL)
                            .addComponent(labelMixFileURL)
                            .addComponent(buttonAddProduct, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 335, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldProductName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(checkBoxInstant)
                .addGap(22, 22, 22)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(buttonProductFile)
                    .addComponent(buttonMixFile))
                .addGap(18, 18, 18)
                .addComponent(labelProductFileURL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(labelMixFileURL)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addComponent(buttonAddProduct)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, 0)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonAddProductActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonAddProductActionPerformed
        ProductType pt = new ProductType();
        if (dbc == null) {

            dbc = Global.getDataBaseConnector();
        }
        try {
            dbc.openSession();
            pt.setType(ptf.getType());
            pt.setEan(ptf.getEan());
            pt.setProductName(textFieldProductName.getText());
            pt.setVersion(dbc.getProductTypeLastVersion(ptf) + 1);
            pt.setFileURL(fileURL);
            pt.setInstant(instant);
            pt.setHidden(hidden);
            if (instant) {

                pt.setFileURLinstant(fileURLInstant);
            }
            pt.setCreateDate(new Timestamp(System.currentTimeMillis()));
            JOptionPane.showMessageDialog(null, "Dodano nową wersję produktu.", "Informacja", JOptionPane.INFORMATION_MESSAGE);
            dbc.saveObject(pt);
        } catch (NullPointerException e) {
            JOptionPane.showMessageDialog(this, "Wybierz plik z nową kartą produktu");
        } catch (Exception e) {
            System.out.println(e.getStackTrace().toString());
            System.out.println(e.toString());
        }
    }//GEN-LAST:event_buttonAddProductActionPerformed

    private void buttonProductFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonProductFileActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("\\\\192.168.17.10\\public"));
        fileChooser.showOpenDialog(this);
        fileURL = fileChooser.getSelectedFile().getAbsolutePath();
        if (fileURL != null) {
            labelProductFileURL.setText(labelFileURLInitValue + fileURL);
            JOptionPane.showMessageDialog(this, "Wybrano plik" + System.lineSeparator() + fileURL);
        } else {
            JOptionPane.showMessageDialog(this, "Proszę ponownie wybrać plik");
        }


    }//GEN-LAST:event_buttonProductFileActionPerformed

    private void buttonMixFileActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonMixFileActionPerformed
        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setCurrentDirectory(new File("\\\\192.168.17.10\\public"));
        fileChooser.showOpenDialog(this);
        fileURLInstant = fileChooser.getSelectedFile().getAbsolutePath();
        if (fileURLInstant != null) {
            labelMixFileURL.setText(labelFileURLInstantInitValue + fileURLInstant);
            JOptionPane.showMessageDialog(this, "Wybrano plik" + System.lineSeparator() + fileURLInstant);
        } else {
            JOptionPane.showMessageDialog(this, "Proszę ponownie wybrać plik");
        }
    }//GEN-LAST:event_buttonMixFileActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buttonAddProduct;
    private javax.swing.JButton buttonMixFile;
    private javax.swing.JButton buttonProductFile;
    private javax.swing.JCheckBox checkBoxInstant;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel labelMixFileURL;
    private javax.swing.JLabel labelProductFileURL;
    private javax.swing.JTextField textFieldProductName;
    // End of variables declaration//GEN-END:variables
}
