/* 
 * Copyright 2018 Cafe Sati Polska.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package Frames.Panels;

import GreenCoffeeClasses.CoffeeCountry;
import GreenCoffeeClasses.CoffeeGreen;
import GreenCoffeeClasses.CoffeeOwner;
import GreenCoffeeClasses.CoffeeType;
import ProductionManagement.DataBaseConnector;
import ProductionManagement.Employee;
import GreenCoffeeClasses.PackType;
import GreenCoffeeClasses.Provider;
import ProductionManagement.Global;
import java.awt.HeadlessException;
import java.util.ArrayList;
import java.util.Arrays;

import javax.swing.JOptionPane;
import javax.swing.SpinnerNumberModel;

/**
 *
 * @author Przemysław
 */
public class EditGreenCoffeePanel extends javax.swing.JPanel {

    /**
     * Creates new form AddGreenCoffeeMagazynierPanel
     */
    ArrayList<CoffeeType> alct;
    ArrayList<CoffeeOwner> alco;
    ArrayList<CoffeeCountry> alcc;
    ArrayList<PackType> alpt;
    ArrayList<Provider> alp;
    Employee emp;
    DataBaseConnector dbc = null;
    CoffeeGreen cg;

    public EditGreenCoffeePanel(CoffeeGreen cg) {
        initComponents();
        this.cg = cg;
        if (dbc == null) {
            dbc = Global.getDataBaseConnector();
        }
        dbc.clearSession();
        dbc.openSession();

        alct = dbc.getCoffeeType();
        Object[] o = alct.toArray();
        Arrays.sort(o);

        comboBoxCoffeeType.removeAllItems();
        for (Object ob : o) {
            CoffeeType ct = (CoffeeType) ob;
            comboBoxCoffeeType.addItem(ct);
        }
        comboBoxCoffeeType.setSelectedItem(cg.getCoffeeType());

        alco = dbc.getCoffeeOwner();
        comboBoxCoffeeOwner.removeAllItems();
        for (CoffeeOwner co : alco) {
            comboBoxCoffeeOwner.addItem(co);
        }
        comboBoxCoffeeOwner.setSelectedItem(cg.getCoffeeOwner());

        alpt = dbc.getPackType();
        comboBoxPackType.removeAllItems();
        for (PackType pt : alpt) {
            comboBoxPackType.addItem(pt);
        }
        comboBoxPackType.setSelectedItem(cg.getPackType());

        alp = dbc.getProvider();
        o = alp.toArray();
        Arrays.sort(o);

        comboBoxProvider.removeAllItems();
        for (Object ob : o) {
            comboBoxProvider.addItem(ob);
        }
        comboBoxProvider.setSelectedItem(cg.getProvider());

        labelCoffeeLabId.setText(cg.getLabId());
        textFieldContractNumber.setText(cg.getContractNumber());
        textFieldDossierNumber.setText(cg.getDossierNumber());
        spinnerPacksNumber.setValue(cg.getNumberOfPacks());
        spinnerCoffeeWeight.setValue(cg.getArrivalWeight());

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        button1 = new java.awt.Button();
        labelCoffeOwner = new javax.swing.JLabel();
        comboBoxCoffeeOwner = new javax.swing.JComboBox();
        comboBoxPackType = new javax.swing.JComboBox();
        labelPackType = new javax.swing.JLabel();
        labelNumberOfPacks = new javax.swing.JLabel();
        labelCoffeeDossierNumber = new javax.swing.JLabel();
        labelContractNumber = new javax.swing.JLabel();
        textFieldContractNumber = new javax.swing.JTextField();
        labelWeight = new javax.swing.JLabel();
        buttonRegisterToLaboratory = new javax.swing.JButton();
        textFieldDossierNumber = new javax.swing.JTextField();
        labelCoffeOwner1 = new javax.swing.JLabel();
        comboBoxCoffeeType = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        comboBoxProvider = new javax.swing.JComboBox();
        spinnerCoffeeWeight = new javax.swing.JSpinner(new SpinnerNumberModel(new Float(0), new Float(0),null,new Float(0.01)))
        ;
        spinnerPacksNumber = new javax.swing.JSpinner();
        labelCoffeeLabId = new javax.swing.JLabel();

        button1.setLabel("button1");

        labelCoffeOwner.setText("Właściciel Kawy");

        comboBoxPackType.setEnabled(false);

        labelPackType.setText("Rodzaj Pakownia");

        labelNumberOfPacks.setText("Ilość Opakowań");

        labelCoffeeDossierNumber.setText("Dossier");

        labelContractNumber.setText("Numer Kontraktu");

        labelWeight.setText("Waga [Kg]");

        buttonRegisterToLaboratory.setText("Zatwierdź zmiany");
        buttonRegisterToLaboratory.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonRegisterToLaboratoryActionPerformed(evt);
            }
        });

        labelCoffeOwner1.setText("Typ kawy");

        jLabel1.setText("Producent");

        spinnerCoffeeWeight.setEnabled(false);

        spinnerPacksNumber.setEnabled(false);

        labelCoffeeLabId.setText("COFFEEID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(labelCoffeeLabId))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(labelCoffeOwner1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCoffeOwner, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(labelNumberOfPacks, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelCoffeeDossierNumber, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(labelContractNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 107, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(textFieldContractNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(1, 1, 1)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(comboBoxCoffeeOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxCoffeeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(comboBoxProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(46, 46, 46))
                            .addComponent(textFieldDossierNumber, javax.swing.GroupLayout.DEFAULT_SIZE, 101, Short.MAX_VALUE)
                            .addComponent(spinnerPacksNumber)))
                    .addComponent(buttonRegisterToLaboratory)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelPackType, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(comboBoxPackType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(labelWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(spinnerCoffeeWeight, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(labelCoffeeLabId)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxCoffeeType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCoffeOwner1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxCoffeeOwner, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelCoffeOwner))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(comboBoxProvider, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCoffeeDossierNumber, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(textFieldDossierNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelContractNumber)
                    .addComponent(textFieldContractNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPackType)
                    .addComponent(comboBoxPackType, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelNumberOfPacks)
                    .addComponent(spinnerPacksNumber, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelWeight)
                    .addComponent(spinnerCoffeeWeight, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(buttonRegisterToLaboratory)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void buttonRegisterToLaboratoryActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonRegisterToLaboratoryActionPerformed
        try {
            dbc.openSession();
            dbc.startTransation();
            cg.setCoffeeOwner((CoffeeOwner) comboBoxCoffeeOwner.getSelectedItem());
            cg.setContractNumber(textFieldContractNumber.getText());
            cg.setCoffeeType((CoffeeType) comboBoxCoffeeType.getSelectedItem());
            cg.setDossierNumber(textFieldDossierNumber.getText());
            cg.setProvider((Provider) comboBoxProvider.getSelectedItem());
            dbc.saveTransation(cg);
            JOptionPane.showMessageDialog(null, "Zmieniono dane.", "Informacja", JOptionPane.INFORMATION_MESSAGE);
            dbc.commitTransation();
        } catch (HeadlessException e) {
            JOptionPane.showMessageDialog(null, "Sprawdź wprowadzone dane", "Błąd", JOptionPane.ERROR_MESSAGE);
            dbc.rollbackTransation();
        }
    }//GEN-LAST:event_buttonRegisterToLaboratoryActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private java.awt.Button button1;
    private javax.swing.JButton buttonRegisterToLaboratory;
    private javax.swing.JComboBox comboBoxCoffeeOwner;
    private javax.swing.JComboBox comboBoxCoffeeType;
    private javax.swing.JComboBox comboBoxPackType;
    private javax.swing.JComboBox comboBoxProvider;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel labelCoffeOwner;
    private javax.swing.JLabel labelCoffeOwner1;
    private javax.swing.JLabel labelCoffeeDossierNumber;
    private javax.swing.JLabel labelCoffeeLabId;
    private javax.swing.JLabel labelContractNumber;
    private javax.swing.JLabel labelNumberOfPacks;
    private javax.swing.JLabel labelPackType;
    private javax.swing.JLabel labelWeight;
    private javax.swing.JSpinner spinnerCoffeeWeight;
    private javax.swing.JSpinner spinnerPacksNumber;
    private javax.swing.JTextField textFieldContractNumber;
    private javax.swing.JTextField textFieldDossierNumber;
    // End of variables declaration//GEN-END:variables
}
