/* 
 * Copyright 2018 Cafe Sati Polska.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package Frames.Panels;

import GreenCoffeeClasses.CoffeeGreenChangeHistory;
import ProductionManagement.Global;
import java.util.Arrays;
import java.util.Set;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Przemysław
 */
public class ShowResourceCoffeeChangeHistoryPanel extends javax.swing.JPanel {

    /**
     * Creates new form ShowResorceChangeHistoryPanel
     *
     * @param hscgch
     */
    public ShowResourceCoffeeChangeHistoryPanel(Set<CoffeeGreenChangeHistory> hscgch) {

        initComponents();

        Object[] ar = hscgch.toArray();
        Arrays.sort(ar);

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

        for (int i = 0; i < ar.length; i++) {

            CoffeeGreenChangeHistory o = (CoffeeGreenChangeHistory) ar[i];
            dtm.addRow(new Object[]{
                Global.timestampToStrDDMMYYYY(o.getChangeTime()), o.getWeight(), o.getComment(), o.getChangedBy().toString()
            }
            );

        }

    }
/*
    public ShowResorceChangeHistoryPanel(Set<AromaChangeHistory> hscgch) {
        initComponents();

        Object[] ar = hscgch.toArray();
        Arrays.sort(ar);

        DefaultTableModel dtm = (DefaultTableModel) jTable1.getModel();

        for (int i = 0; i < dtm.getRowCount(); i++) {

            CoffeeGreenChangeHistory o = (CoffeeGreenChangeHistory) ar[i];
            dtm.addRow(new Object[]{
                Global.timestampToStrDDMMYYYY(o.getChangeTime()), o.getWeight(), o.getComment(), o.getChangedBy().toString()
            }
            );

        }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Data", "Zmiana", "Komentarz", "Zmienił"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Float.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, true, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 661, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(14, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
